<?php

putenv('DISPLAY_ERROS_DETAILS =' . false);

putenv('RISTORANTEGIANLUCA_FRANQUIAS_MYSQL_HOST=');
putenv('RISTORANTEGIANLUCA_FRANQUIAS_MYSQL_DBNAME=');
putenv('RISTORANTEGIANLUCA_FRANQUIAS_MYSQL_USER=');
putenv('RISTORANTEGIANLUCA_FRANQUIAS_MYSQL_PASSWORD=');
putenv('RISTORANTEGIANLUCA_FRANQUIAS_MYSQL_PORT=');

putenv('JWT_SECRET_KEY=');